using System;
using System.Linq;
using System.Windows;
using StudentManagementBusinessObject;
using OnlineEduTaskRepository.Repositories;
using OnlineEduTaskServices.Services;

namespace OnlineEduTaskWPF
{
    public partial class AddStudentDialog : Window
    {
        private readonly StudentService _studentService;
        private readonly UserAccountService _userService;
        private readonly StudentClassService _classService;

        public bool IsSuccess { get; private set; }

        public AddStudentDialog()
        {
            InitializeComponent();
            
            _studentService = new StudentService(new StudentRepository());
            _userService = new UserAccountService(new UserAccountRepository());
            _classService = new StudentClassService(new StudentClassRepository());
            
            LoadClasses();
        }

        private void LoadClasses()
        {
            try
            {
                var classes = _classService.GetAllClasses();
                cmbClass.ItemsSource = classes;
            }
            catch (Exception ex)
            {
                ShowError($"Error loading classes: {ex.Message}");
            }
        }

        private void btnAdd_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                // Validate input
                if (string.IsNullOrWhiteSpace(txtStudentCode.Text))
                {
                    ShowError("Student Code is required");
                    return;
                }

                if (string.IsNullOrWhiteSpace(txtFullName.Text))
                {
                    ShowError("Full Name is required");
                    return;
                }

                if (string.IsNullOrWhiteSpace(txtEmail.Text))
                {
                    ShowError("Email is required");
                    return;
                }

                if (cmbClass.SelectedValue == null)
                {
                    ShowError("Please select a class");
                    return;
                }

                if (string.IsNullOrWhiteSpace(txtUsername.Text))
                {
                    ShowError("Username is required");
                    return;
                }

                if (string.IsNullOrWhiteSpace(txtPassword.Password))
                {
                    ShowError("Password is required");
                    return;
                }

                // Check if username exists
                if (_userService.UsernameExists(txtUsername.Text))
                {
                    ShowError("Username already exists");
                    return;
                }

                // Create Student (StudentId will be auto-generated by database)
                var student = new Student
                {
                    StudentCode = txtStudentCode.Text.Trim(),
                    FullName = txtFullName.Text.Trim(),
                    Email = txtEmail.Text.Trim(),
                    ClassId = (int)cmbClass.SelectedValue
                };

                _studentService.AddStudent(student);
                
                // Get the newly created student ID
                var createdStudent = _studentService.GetAllStudents()
                    .FirstOrDefault(s => s.StudentCode == student.StudentCode && s.Email == student.Email);
                
                if (createdStudent == null)
                {
                    ShowError("Failed to create student");
                    return;
                }

                // Create UserAccount (UserAccountId will be auto-generated by database)
                var userAccount = new UserAccount
                {
                    Username = txtUsername.Text.Trim(),
                    Password = txtPassword.Password,
                    Role = "Student",
                    StudentId = createdStudent.StudentId,
                    TeacherId = null
                };

                _userService.AddUser(userAccount);

                IsSuccess = true;
                MessageBox.Show("Student added successfully!", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
                this.Close();
            }
            catch (Exception ex)
            {
                ShowError($"Error adding student: {ex.Message}");
            }
        }

        private void btnCancel_Click(object sender, RoutedEventArgs e)
        {
            IsSuccess = false;
            this.Close();
        }

        private void ShowError(string message)
        {
            txtError.Text = message;
            txtError.Visibility = Visibility.Visible;
        }
    }
}
